# NumPy - Basics

## Vector - 1D

In [3]:
import numpy as np

In [4]:
my_list = [1,2,3,4,5]

In [5]:
np.array(my_list)

array([1, 2, 3, 4, 5])

## Matrices - 2D

In [6]:
my_matrices = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrices)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## arange function

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)
#2 is step size here

array([0, 2, 4, 6, 8])

## zeros function

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Ones function

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## Linspace function - One D array

In [18]:
np.linspace(1,2,3)
# start,stop,stepsize

array([1. , 1.5, 2. ])

## Identity Matrix - Diagonal is 1 and Rest is 0

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random function

### rand function

In [20]:
np.random.rand(5)

array([0.67543535, 0.33145352, 0.63963881, 0.21456049, 0.0113133 ])

In [22]:
np.random.rand(5,5)

array([[0.06449232, 0.53019221, 0.94675418, 0.23694215, 0.05315691],
       [0.21331369, 0.98647346, 0.1207731 , 0.88309509, 0.32904429],
       [0.89332662, 0.56579677, 0.78377018, 0.96627828, 0.67040751],
       [0.3861202 , 0.78653764, 0.428841  , 0.49891582, 0.0570277 ],
       [0.00393826, 0.24105385, 0.24776141, 0.30328492, 0.0532359 ]])

### randn - Numbers from standard Normal distribution 

In [24]:
np.random.randn(4)

array([ 1.4991713 , -0.2942485 ,  0.70450959,  2.57262738])

In [26]:
np.random.randn(3,4)

array([[ 2.19241498, -0.40140631,  0.30330594, -1.04261551],
       [-1.42666095,  0.34803168, -0.3035071 , -0.30547551],
       [ 0.47024329, -0.33956435,  1.44558613,  0.93119265]])

### randint - random numbers from low to high

In [28]:
np.random.randint(0,100,10)
#low(inclusive),high(exclusive),N

array([47, 85, 94, 26, 48, 71, 12, 67, 73, 13])

## reshape function

In [33]:
# reshape size should be equal to array size 
# eg if arr has array size 25, then (5,5) reshape will have perfect 5x5 numbers to fill-in

In [30]:
arr = np.arange(25)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

## Max/Min/argmax/argmin function

In [34]:
randarr = np.random.randint(0,50,10)

In [35]:
randarr

array([48, 44, 47, 37, 31, 37, 23, 43, 25, 33])

In [36]:
randarr.max()

48

In [37]:
randarr.min()

23

In [39]:
randarr.argmax()

0

In [40]:
randarr.argmin()

6

## shape

In [42]:
randarr.shape

(10,)

In [45]:
arr = arr.reshape(5,5)

In [47]:
arr.shape

(5, 5)

## dtype

In [48]:
arr.dtype

dtype('int32')

## importing functions - shortcut

In [49]:
#instead of writing np.random.randint we can use as below:
from numpy.random import randint

In [54]:
randint(5,10,10)

array([6, 8, 5, 9, 6, 8, 8, 6, 6, 6])

In [56]:
randint(5,10)

8