# NumPy Array Indexing

In [2]:
import numpy as np

## NumPy slice notation

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcast operation

In [11]:
arr[0:5] = 100

In [12]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [14]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
slice_of_array = arr[0:6]

In [19]:
slice_of_array

array([0, 1, 2, 3, 4, 5])

In [20]:
slice_of_array[:] = 100

In [21]:
slice_of_array

array([100, 100, 100, 100, 100, 100])

In [22]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

## Copy of an array

In [23]:
slice_of_array = arr.copy()

In [24]:
slice_of_array

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [25]:
slice_of_array[:]=100

In [26]:
slice_of_array

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr

array([100, 100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

## 2D Array

In [47]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr_2d[1,1]

5

In [50]:
arr_2d[1][1]

5

In [53]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [54]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

## Boolean comparison

In [59]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [60]:
arr>5

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [61]:
arr >100

array([False, False, False, False, False, False, False, False, False,
       False, False])

In [63]:
boolarr = arr>5
boolarr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [65]:
arr[boolarr]
#returns true values

array([ 6,  7,  8,  9, 10])

In [71]:
arr[boolarr != True]

array([0, 1, 2, 3, 4, 5])

In [73]:
#shortcut
arr[arr>5]

array([ 6,  7,  8,  9, 10])

## Array with Array operations

In [77]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [79]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [80]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Array with Scalar

In [81]:
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [82]:
arr * 100

array([ 100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

## Numpy issues warning for an error and not exception error

In [83]:
1/0

ZeroDivisionError: division by zero

In [88]:
arr/0

C:\Users\nabhs\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

## Other basic functions

In [89]:
np.max(arr)

10

In [90]:
np.min(arr)

1

In [91]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [92]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [93]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [94]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])